return {
  ui = { border = "rounded" },
  ensure_installed = {
    "astro-language-server",
    "bash-language-server",
    "beautysh",
    "biome",
    "clang-format",
    "clangd",
    "codelldb",
    "css-lsp",
    "debugpy",
    "dprint",
    "djlint",
    "gopls",
    "html-lsp",
    "json-lsp",
    "lua-language-server",
    "marksman",
    "markdownlint",
    "mdformat",
    "mypy",
    "python-lsp-server",
    "pyright",
    "prettier",
    "ruff-lsp",
    "rust-analyzer",
    "shellcheck",
    "stylua",
    "stylelint",
    "tailwindcss-language-server",
    "typescript-language-server",
  },
}
