return {
  "mg979/vim-visual-multi",
  cmd = {
    "VMap",
    "VNew",
    "VNewShell",
    "VS",
    "VSCode",
    "VSDebug",
    "VSDebugger",
    "VSTerminal",
    "VSTerminalOpen",
    "VSTerminalSend",
    "VSTerminalSendRaw",
    "VSTerminalToggle",
    "VSTerminalToggleSplit",
    "VSTerminalVSCode",
    "VSTerminalWindows",
    "VToggle",
    "VToggleLine",
    "VToggleRange",
    "VW",
    "VWSplit",
  },
}
