return {
  "williamboman/mason.nvim",
  opts = {
    ui = { border = "rounded" },
    ensure_installed = {
      "astro-language-server",
      "bash-language-server",
      "beautysh",
      "biome",
      "clang-format",
      "clangd",
      "codelldb",
      "css-lsp",
      "debugpy",
      "dprint",
      "djlint",
      "gopls",
      "haskell-language-server",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "markdownlint",
      "mdformat",
      "mypy",
      "ocaml-lsp",
      "python-lsp-server",
      "pyright",
      "prettier",
      "ruff-lsp",
      "rust-analyzer",
      "shellcheck",
      "stylua",
      "stylelint",
      "taplo",
      "tailwindcss-language-server",
      "typescript-language-server",
    },
  },
}
