return {
  { import = "plugins.gale.flipflop" },
  { import = "plugins.gale.popurri" },
  { import = "plugins.gale.yerbreak" },
  { import = "plugins.spec.autosession", enabled = false },
  { import = "plugins.spec.barbecue", enabled = false },
  { import = "plugins.spec.better-escape" },
  { import = "plugins.spec.ccc" },
  { import = "plugins.spec.codecompanion" },
  { import = "plugins.spec.crates", enabled = false },
  { import = "plugins.spec.dap-python" },
  { import = "plugins.spec.dap-ui" },
  { import = "plugins.spec.dap-virtual-text" },
  { import = "plugins.spec.dressing", enabled = false },
  { import = "plugins.spec.dropbar" },
  { import = "plugins.spec.edgy" },
  { import = "plugins.spec.gitsigns" },
  { import = "plugins.spec.grug-far" },
  { import = "plugins.spec.fine-cmdline", enabled = false },
  { import = "plugins.spec.fugitive" },
  { import = "plugins.spec.go", enabled = false },
  { import = "plugins.spec.gleam", enabled = false },
  { import = "plugins.spec.harpoon" },
  { import = "plugins.spec.hop" },
  { import = "plugins.spec.hover" },
  { import = "plugins.spec.lspsaga" },
  { import = "plugins.spec.lsp-signature", enabled = false },
  { import = "plugins.spec.matchup" },
  { import = "plugins.spec.md-preview" },
  { import = "plugins.spec.neocomposer", enabled = false },
  { import = "plugins.spec.notify" },
  { import = "plugins.spec.project", enabled = false },
  -- TODO: re-enable once html support improves
  { import = "plugins.spec.rainbow-delimiters", enabled = false },
  { import = "plugins.spec.regexplainer" },
  { import = "plugins.spec.rustaceanvim" },
  { import = "plugins.spec.scrolleof" },
  { import = "plugins.spec.searchbox", enabled = false },
  { import = "plugins.spec.swenv", enabled = false },
  { import = "plugins.spec.tabby-ml" },
  { import = "plugins.spec.todo-comments" },
  { import = "plugins.spec.treesitter-textobjects" },
  { import = "plugins.spec.ts-autotag" },
  { import = "plugins.spec.ts-context-commentstring" },
  { import = "plugins.spec.tstools" },
  { import = "plugins.spec.undo-tree" },
  { import = "plugins.spec.vim-astro" },
  { import = "plugins.spec.zen-mode" },
}
